// USERS ERRORS

export const CREDENTIALS_ALREADY_EXIST = 'CREDENTIALS_ALREADY_EXIST';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_CANNOT_BE_DELETED = 'USER_CANNOT_BE_DELETED';
export const BAD_CREDENTIALS = 'BAD_CREDENTIALS';
export const ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND';

// POSTS ERRORS

export const POST_COULD_NOT_BE_CREATED = 'POST_COULD_NOT_BE_CREATED';
export const POST_NOT_FOUND = 'POST_NOT_FOUND';
export const POST_CANNOT_BE_DELETED = 'POST_CANNOT_BE_DELETED';

// LIKES ERRORS
export const LIKE_COULD_NOT_BE_CREATED = 'LIKE_COULD_NOT_BE_CREATED';
export const LIKE_CANNOT_BE_DELETED = 'LIKE_CANNOT_BE_DELETED';

// COMMENTS ERRORS
export const COMMENT_COULD_NOT_BE_CREATED = 'COMMENT_COULD_NOT_BE_CREATED';
export const COMMENT_CANNOT_BE_DELETED = 'COMMENT_CANNOT_BE_DELETED';
